### ISSUE TITLE
Preenchimento incompleto do readme

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/IoThinking#2]
Falta: 

- justificativa do projeto
- especificação do papel de cada membro

**Comment by jorgehclinhares** [comment]
- falta tbm a descrição do produto

**Comment by fnnncin** [comment]
OK. Hoje, nós iremos colocar essas informações.
Em 08/04/2016 12:45, "Jorge Linhares" <notifications@github.com> escreveu:

**Comment by jorgehclinhares** [comment]
Blz

**Comment by fnnncin** [comment]
Atualizamos nosso repositório.
Em 09/04/2016 20:17, "Jorge Linhares" <notifications@github.com> escreveu:

**Comment by jorgehclinhares** [comment]
Ainda falta:

- [ ] Justificativa do projeto
- [ ] Especificação do papel de cada membro

Se tiverem alguma dúvida, podem falar.

**Comment by fnnncin** [comment]
Jorge, fizemos mais uma edição hj e colocamos um parágrafo para a
justificativa e especificamos os papéis dos membros.
Em 11/04/2016 11:13 AM, "Jorge Linhares" <notifications@github.com>
escreveu:

**Comment by jorgehclinhares** [comment]
@fnnncin show!
