### ISSUE TITLE
Reunião emergencial

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/IoThinking#8]
Pessoal, preciso esclarecer algumas coisas com vocês. Então, assim como eu fiz com a outra equipe que eu monitoro, gostaria de marcar com vocês uma reunião emergencial. Pode ser presencial ou remota, vcs decidem o dia. Tenho maior disponibilidade na quarta para ser remoto e terça e quinta presencial. Mas a gente pode ver um horário fora dos que eu já disse.

**Comment by PedroClericuzi** [comment]
Pra mim rola tanto na terça, mas só de 18h às 19h, quanto na quarta depois das 19h.

**Comment by jorgehclinhares** [comment]
Na terça eu to em aula, na quarta pode ser remoto

**Comment by NascimentoSilva** [comment]
Na quarta a partir das 19h estou disponível.

**Comment by PedroClericuzi** [comment]
Oi @jorgehclinhares, tudo certo? Vai rolar a reunião agr?

**Comment by jorgehclinhares** [comment]
Remoto? Pode ser agora

**Comment by jorgehclinhares** [comment]
E chama no facebook pfvor

**Comment by jorgehclinhares** [comment]
Realizada
